# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12node_service.proto\x12\x0cnode_service\"9\n\x0eMessageRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x14\n\x0cmessage_text\x18\x02 \x01(\t\")\n\x0cMessageReply\x12\x19\n\x11\x63onfirmation_text\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\")\n\x13HealthCheckResponse\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\";\n\x06Tensor\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"V\n\rTensorRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0btensor_data\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\"d\n\x0eTensorResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x30\n\rresult_tensor\x18\x02 \x01(\x0b\x32\x14.node_service.TensorH\x00\x88\x01\x01\x42\x10\n\x0e_result_tensor2\xe6\x01\n\x0bNodeService\x12G\n\x0bSendMessage\x12\x1c.node_service.MessageRequest\x1a\x1a.node_service.MessageReply\x12\x45\n\x0bHealthCheck\x12\x13.node_service.Empty\x1a!.node_service.HealthCheckResponse\x12G\n\nSendTensor\x12\x1b.node_service.TensorRequest\x1a\x1c.node_service.TensorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=36
  _globals['_MESSAGEREQUEST']._serialized_end=93
  _globals['_MESSAGEREPLY']._serialized_start=95
  _globals['_MESSAGEREPLY']._serialized_end=136
  _globals['_EMPTY']._serialized_start=138
  _globals['_EMPTY']._serialized_end=145
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=147
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=188
  _globals['_TENSOR']._serialized_start=190
  _globals['_TENSOR']._serialized_end=249
  _globals['_TENSORREQUEST']._serialized_start=251
  _globals['_TENSORREQUEST']._serialized_end=337
  _globals['_TENSORRESPONSE']._serialized_start=339
  _globals['_TENSORRESPONSE']._serialized_end=439
  _globals['_NODESERVICE']._serialized_start=442
  _globals['_NODESERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
